### ISSUE TITLE
"Ensuring webhooks" feature panics

### ISSUE THREAD

**Issue by bauerjs1** [zapier/kubechecks#68]
If I understand correctly, setting the flag `KUBECHECKS_ENSURE_WEBHOOKS` should make Kubecheck autoconfigure its webhook for all known repositories in the VCS via API calls, right?

I wanted to give that option a try so I don't have to configure all repositories manually, but it is failing with the following error:
```
10:53AM DBG Debug level logging enabled.
10:53AM TRC Trace level logging enabled.
10:53AM INF Initialized logger.
10:53AM INF setting logrus log level log_level=error
10:53AM INF Initializing telemetry
10:53AM INF otel disabled
10:53AM INF Server Configuration:
10:53AM INF Webhook URL Base: https://kubechecks.mycompany.com
10:53AM INF Webhook URL Prefix:
10:53AM INF VCS Type: gitlab
Starting KubeChecks: 24h b94b428
10:53AM DBG building VCS to Application Map
10:53AM INF ensuring all webhooks are created correctly
10:53AM DBG Token Length - 26
10:53AM INF webhook URL for this kubechecks instance webhookUrl=https://kubechecks.mycompany.com/hooks/gitlab/project
10:53AM ERR could not parse GitLab URL error="repository host 'git.mycompany.com' not supported" url=git@git.mycompany.com:k8s/namespaces/security
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2a3718f]

goroutine 98 [running]:
github.com/zapier/kubechecks/pkg/gitlab_client.parseRepoName({0xc0010a7000, 0x3a}
	/src/pkg/gitlab_client/client.go:126 +0xa
github.com/zapier/kubechecks/pkg/gitlab_client.(*Client).GetHookByUrl(0xc00063d110, {0x33bd147?, 0x28?}, {0xc0010a7000?, 0x37?}, {0xc00016bc20, 0x37}
	/src/pkg/gitlab_client/client.go:130 +0x4
github.com/zapier/kubechecks/pkg/server.(*Server).ensureWebhooks(0xc00063d140
	/src/pkg/server/server.go:107 +0x42
github.com/zapier/kubechecks/pkg/server.(*Server).Start(0xc00063d140
	/src/pkg/server/server.go:43 +0x9
created by github.com/zapier/kubechecks/cmd.glob..func
	/src/cmd/controller_cmd.go:32 +0x205
```

I am using the temporary build from #55 (with the fix for custom vcs URLs) and the following settings:
```yaml
KUBECHECKS_ARGOCD_API_INSECURE: true
KUBECHECKS_ARGOCD_API_SERVER_ADDR: argocd.mycompany.com
KUBECHECKS_ARGOCD_WEBHOOK_URL: https://argocd.mycompany.com/api/webhook
KUBECHECKS_ENSURE_WEBHOOKS: true
KUBECHECKS_LOG_LEVEL: trace
KUBECHECKS_MONITOR_ALL_APPLICATIONS: true
KUBECHECKS_NAMESPACE: gitlab
KUBECHECKS_WEBHOOK_URL_BASE: https://kubechecks.mycompany.com
KUBECHECKS_VCS_BASE_URL: https://git.mycompany.com
KUBECHECKS_VCS_TYPE: gitlab
```

Thanks again and cheers

**Comment by djeebus** [comment]
Hehe, you're finding all kinds of fun new issues with this new feature. Let me see what I can do here.

**Comment by djeebus** [comment]
Try the temporary image from #69 , see if it fixes the issue?

**Comment by bauerjs1** [comment]
It does, all my repos now have a webhook configured. Awesome! 🎉 

Probably unrelated: Kubechecks logs
```
could not retrieve pipeline status after multiple attempts
```
after being triggered. However, I can see no issues in my merge requests (there even pops up an additional pipeline stage with a successfully completed "Kubechecks" job)
